bag_button_pos = { x = 320, y = 1220 }

bag_first_grid_center_pos = { x = 50, y = 810 }

bag_grid_size = { width = 90, height = 90 }

back_pos = { x = 320, y = 40 }

bag_1_pos = { x = 80, y = 670 }

bag_2_pos = { x = 200, y = 670 }

equipment_names = [
    "链",
    "戒",
    "时装",
    "衣",
    "护手",
    "鞋",
    "裤",
    "腰带",
    "背",
    "头",
    "肩",
    "护符",
    "坐骑",
    "副手",
    "单手刀",
    "单手剑",
    "双手刀",
    "双手剑",
    "法器",
    "法杖",
    "轻弩",
    "重型武器",
    "重弩",
    "长柄武器",
    "弓箭",
    "杖",
    "腰"
]

remove_item_names = [
    "防具箱（锁）",
    "服饰箱（锁）",
    "防具箱（锁）",
    "武器箱（锁）",
    "秘宝礼包（锁）",
    "治疗药水",
    "法力药水",
    "月狼之石",
    "腐鹰羽毛",
    "灵草",
    "被咬过的肉",
    "断骨",
    "毒舌",
    "腐尸",
    "鹰身人的羽毛",
    "业火",
    "死心",
    "断弩",
    "腐肉",
    "药果",
    "双头犬的肉",
    "灵魂结晶",
    "英雄证明",
    "杜时雨的颜料",
    "竹子",
    "药果",
    "英雄证明",
    "兑换铜币",
    "灵魂结晶",
    "豹皮",
    "三级碎木",
    "三级碎石",
    "三级碎矿",
    "四级碎木",
    "四级碎石",
    "四级碎矿",
    "五级碎木",
    "五级碎石",
    "五级碎矿",
    "冰雪披风",
    "美女节时装（2天）",
    "黑魔一族护符（1天）",
    "屠龙勇士称号"
]

#    普通
#    Common,
#    精致
#    Fine,
#    稀有
#    Rare,
#    史诗
#    Epic,
#    传说
#    Legendary,
remove_item_raritys = [
    "Common",
    "Fine",
]

# 装备
# Equipment,
# 任务物品
# QuestItem,
# 道具消耗品
# Consumable,
# 建筑材料
# BuildingMaterials,
# 特殊
# SpecialItem,
# 宠物
# Pet,
remove_item_types = [
    "Equipment"
]
